name: Terratest

on: push

env:
  TF_IN_AUTOMATION: "True"
  CLOUDAMQP_APIKEY: ${{ secrets.CLOUDAMQP_APIKEY }}

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terratest
        uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: tests